Implement classworkService.findClassworkAssignmentsById
duongdev/kathena pull request #311
Opened 2021-05-17 03:21 UTC by HuynhThanhCanh

- Wrote service, resolver and unit test
Link task: https://app.clickup.com/t/89xga5

2021-05-20 09:14 UTC, danghieuliem requested changes

2021-05-20 09:14 UTC, danghieuliem commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    @Args('orgId', { type: () => ID }) orgId: string,
CurrentOrg rồi mà còn truyền orgID :D

2021-05-21 01:25 UTC, nhatminh0509 approved these changes

2021-05-24 03:49 UTC, danghieuliem approved these changes

2021-05-24 06:26 UTC, nguyenvanhai-0911 approved these changes

2021-05-24 06:31 UTC, duongdev approved these changes

2021-05-24 06:31 UTC, merged