Implement classworkService.updateClassworkAssignment
duongdev/kathena pull request #329
Opened 2021-05-19 13:32 UTC by nguyenvanhai-0911

Link task: https://app.clickup.com/t/89xg8f

2021-05-20 10:59 UTC, nhatminh0509 requested changes

2021-05-20 10:59 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    @Args('courseId', { type: () => ID }) courseId: string,
courseId define but never used

2021-05-21 01:49 UTC, nhatminh0509 approved these changes

2021-05-21 04:31 UTC, HuynhThanhCanh approved these changes

2021-05-21 07:06 UTC, danghieuliem approved these changes

2021-05-21 07:07 UTC, danghieuliem requested changes
fix bug đi ông

2021-05-21 07:10 UTC, nguyenvanhai-0911 commented
đang build lại nha ông

2021-05-21 07:15 UTC, danghieuliem approved these changes

2021-05-21 07:17 UTC, merged