Implement classworkService.updateClassworkAssignmentPublication
duongdev/kathena pull request #333
Opened 2021-05-20 05:50 UTC by nguyenvanhai-0911

Link task: https://app.clickup.com/t/89xg8t

2021-05-20 10:56 UTC, nhatminh0509 requested changes
còn 1 vấn đề không liên quan lắm nhưng cần lưu ý, nên handle các lổi có thể trước khi thực hiện query find để tăng performance

2021-05-20 10:56 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classwork.service.ts
> +      orgId: string
orgId define but never used

2021-05-20 10:56 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classwork.service.ts
> +      query.id,
nên find thêm orgId tại đây

2021-05-21 01:46 UTC, nhatminh0509 reviewed
Nên như vầy nè

2021-05-21 01:46 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classwork.service.ts
> +    }
```suggestion
    if (
      !(await this.authService.canAccountManageCourse(
        query.accountId,
        classworkAssignment.courseId,
      ))
    ) {
      throw new Error(`ACCOUNT_CAN'T_MANAGE_COURSE`)
    }

    const classworkAssignment = await this.classworkAssignmentsModel.findById(
      query.id,
      query.orgId,
    )

    if (!classworkAssignment) {
      throw new Error(
        `Couldn't find classworkAssignment to update publicationState`,
      )
    }
```

2021-05-21 01:58 UTC, nhatminh0509 approved these changes

2021-05-21 04:26 UTC, HuynhThanhCanh approved these changes

2021-05-21 07:57 UTC, danghieuliem approved these changes

2021-05-21 07:59 UTC, merged