Cu 8p0f3z fe implement list classwork material page
duongdev/kathena pull request #353
Opened 2021-05-25 03:21 UTC by kugayamashusei

Link task: https://app.clickup.com/t/8p0f3z
1.Khi không có tài liệu
![image](https://user-images.githubusercontent.com/58841667/119434657-d4c36b00-bd42-11eb-9850-9b7bc63e84bb.png)

2. Khi có tài liệu:
![image](https://user-images.githubusercontent.com/58841667/119434685-e573e100-bd42-11eb-9c20-7c3f01920f28.png)

2021-05-25 03:21 UTC, duongdev commented
Task linked: [CU-8p0f3z [FE] Implement list classwork material Page](https://app.clickup.com/t/8p0f3z)

2021-05-25 03:37 UTC, nhatminh0509 requested changes

2021-05-25 03:37 UTC, nhatminh0509 commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
này sai rồi ông có 2 param id kìa

2021-05-25 03:40 UTC, danghieuliem approved these changes

2021-05-25 05:57 UTC, kugayamashusei commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
để tui sửa lại xí, tại đang test làm đường dẫn qua để tạo thử.

2021-05-25 06:33 UTC, kugayamashusei commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
@nhatminh0509  xong nhé

2021-05-25 08:51 UTC, nhatminh0509 commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
tui nghĩ là xóa luôn cái icon ở đâu luôn đi

2021-05-26 06:07 UTC, kugayamashusei commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
ok

2021-05-26 06:09 UTC, kugayamashusei commented on packages/web/src/utils/path-builder.ts
> +export const CREATE_TEACHING_COURSE_CLASSWORK_MATERIALS = `${TEACHING_COURSE_CLASSWORK_MATERIALS}/:id/create/`
![image](https://user-images.githubusercontent.com/58841667/119610479-7f12bf80-be23-11eb-9d90-9a63a13bb7db.png)
xong nhé

2021-05-26 09:20 UTC, nhatminh0509 approved these changes

2021-05-26 09:22 UTC, merged