[WIP] [CLONE] Implement add and remove attachments function for classwork material and classwork assignments
duongdev/kathena pull request #354
Opened 2021-05-25 08:49 UTC by HuynhThanhCanh

2021-05-25 08:49 UTC, duongdev commented
Task linked: [CU-8r1zcb [BE] Implement add and remove attachments function for classwork material and classwork assignments](https://app.clickup.com/t/8r1zcb)

2021-05-25 09:03 UTC, danghieuliem approved these changes

2021-05-25 09:14 UTC, nhatminh0509 requested changes

2021-05-25 09:14 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    //
theo như kinh nghiệm debug bằng đầu và nhân số học :)) thì thông điệp của vũ trụ gửi đến cho tui thấy có lẽ listFileId ở vị trí này đang là rỗng.

2021-05-25 09:18 UTC, nguyenvanhai-0911 approved these changes

2021-05-25 09:31 UTC, HuynhThanhCanh commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    //
Dòng 156 - 163 đang await nên dòng 165 không thể chạy trước khi dòng 156 - 163 chưa chạy xong, nên sẽ ko rỗng =))

2021-05-25 09:51 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    //
ko, nó rỗng sau if ý

2021-05-25 13:53 UTC, HuynhThanhCanh commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    //
sao rỗng được nhỉ, ông có thể giải thích giúp tui dc ko? @nhatminh0509

2021-05-26 03:06 UTC, nhatminh0509 commented on packages/server/src/modules/classwork/classworkAssignments.resolver.ts
> +    //
demo xong còn cãi nữa ko :))) đã nói là thông điệp vũ trũ gửi tới mà :)))

2021-05-26 04:01 UTC, nhatminh0509 approved these changes

2021-05-26 04:01 UTC, nhatminh0509 commented
anh @duongdev xem lại giúp em ạ

2021-05-26 04:08 UTC, duongdev approved these changes

2021-05-26 04:15 UTC, merged