Cu 8fvwrq fe create classwork material page
duongdev/kathena pull request #367
Opened 2021-05-27 07:33 UTC by kugayamashusei

1. Link task: https://app.clickup.com/t/8fvwrq
1. Giao diện 
Hiện tại bên backend chỉ cho phép tạo title, description, publicationState nên giao diện sẽ là: 
![image](https://user-images.githubusercontent.com/58841667/119783908-e4d07b80-bef7-11eb-9b07-3dd6fae8c13d.png)
2. Phần tạo tài liệu khi tạo thiếu dữ liệu đầu vào
![image](https://user-images.githubusercontent.com/58841667/119784396-5ad4e280-bef8-11eb-967b-6053f075490d.png)
3. Khi tạo thành công
![image](https://user-images.githubusercontent.com/58841667/119784472-6fb17600-bef8-11eb-95ff-82fe50581671.png)
![image](https://user-images.githubusercontent.com/58841667/119784487-75a75700-bef8-11eb-8f62-a19dcd51dca2.png)

2021-05-27 07:33 UTC, duongdev commented
Task linked: [CU-8fvwrq [FE] Create classwork material Page](https://app.clickup.com/t/8fvwrq)

2021-05-27 12:54 UTC, nhatminh0509 reviewed
BE đã thêm file được rồi á, ông update thêm cái đó đi

2021-05-28 02:44 UTC, kugayamashusei commented
> BE đã thêm file được rồi á, ông update thêm cái đó đi

HIện tại backend đang bị lỗi, nên chưa sửa được ngay bây giờ nha.

2021-05-28 03:53 UTC, kugayamashusei commented
Cập nhật mới:
1. Giao diện:
![image](https://user-images.githubusercontent.com/58841667/119925850-6aa80180-bfa0-11eb-8f11-e7170e51c46f.png)
2. Thêm thất bại:
![image](https://user-images.githubusercontent.com/58841667/119926380-81028d00-bfa1-11eb-881d-f0f20cf86ef7.png)
3. Thêm thành công
![image](https://user-images.githubusercontent.com/58841667/119926432-9ecff200-bfa1-11eb-96e2-b09d2bbb2b43.png)
![image](https://user-images.githubusercontent.com/58841667/119927056-d8552d00-bfa2-11eb-880e-e588fd6ce605.png)
4. Dữ liệu trong mongoDB
![image](https://user-images.githubusercontent.com/58841667/119927096-f589fb80-bfa2-11eb-9c01-f6e529744016.png)

2021-05-28 04:19 UTC, nhatminh0509 requested changes
Bỏ cái field Trạng thái đi, bây giờ theo ý anh Dương thì trạng thái được thêm bằng 2 button (Lưu nháp và Đăng)

2021-05-28 04:32 UTC, kugayamashusei commented
> Bỏ cái field Trạng thái đi, bây giờ theo ý anh Dương thì trạng thái được thêm bằng 2 button (Lưu nháp và Đăng)

ok

2021-05-28 04:42 UTC, kugayamashusei commented
> > Bỏ cái field Trạng thái đi, bây giờ theo ý anh Dương thì trạng thái được thêm bằng 2 button (Lưu nháp và Đăng)
> 
> ok

Xong nhé 
![image](https://user-images.githubusercontent.com/58841667/119930477-b6ab7400-bfa9-11eb-80aa-46c9e90b7d27.png)

2021-05-28 04:43 UTC, duongdev commented
MUI có support cái nút giống vầy ko?

![image](https://user-images.githubusercontent.com/9253690/119930585-e9556c80-bfa9-11eb-95e8-084e3db09d79.png)

2021-05-28 04:44 UTC, duongdev commented
nè @kugayamashusei 
https://next.material-ui.com/components/button-group/#split-button

2021-05-28 04:53 UTC, nhatminh0509 commented
> MUI có support cái nút giống vầy ko?
> 
> ![image](https://user-images.githubusercontent.com/9253690/119930585-e9556c80-bfa9-11eb-95e8-084e3db09d79.png)

có á anh

2021-05-28 13:11 UTC, kugayamashusei commented
> nè @kugayamashusei 
> https://next.material-ui.com/components/button-group/#split-button

Là giờ em làm gì với cái này á anh @duongdev

2021-05-28 16:15 UTC, duongdev commented
Xong update lại hình nha

2021-05-28 16:15 UTC, duongdev commented
> > nè @kugayamashusei 
> > https://next.material-ui.com/components/button-group/#split-button
> 
> Là giờ em làm gì với cái này á anh @duongdev 

Làm 2 cái action như a nói á

2021-05-31 07:49 UTC, kugayamashusei commented
![image](https://user-images.githubusercontent.com/58841667/120159376-5887c680-c21f-11eb-86ca-66a507509c59.png)
Update xong rồi nha @nhatminh0509

2021-05-31 07:54 UTC, nhatminh0509 requested changes
SplitButton ở kathena ui có rồi mà sử dụng lại được á, không cần tạo lại trong components đâu @kugayamashusei

2021-05-31 07:59 UTC, kugayamashusei commented
> SplitButton ở `@kathena-ui` có rồi mà sử dụng lại được á, không cần tạo lại trong components đâu @kugayamashusei

ok để xóa

2021-05-31 11:07 UTC, duongdev approved these changes

2021-05-31 11:16 UTC, nhatminh0509 approved these changes

2021-05-31 11:17 UTC, merged