[BE] Implement academicService.findLessonById
duongdev/kathena pull request #646
Opened 2021-08-22 18:08 UTC by danghieuliem

2021-08-22 18:08 UTC, duongdev commented
Task linked: [CU-bng7j6 [BE] Implement academicService.findLessonById](https://app.clickup.com/t/bng7j6)

2021-08-23 03:04 UTC, canhuyh requested changes

2021-08-23 03:04 UTC, canhuyh commented on packages/server/src/modules/academic/academic.service.spec.ts
> +          .mockResolvedValueOnce(lesson as ANY)
tui thấy khúc này không nên mock mà mình sẽ create để hàm tự find luôn thì sẽ chuẩn xác hơn, vì hàm này đang là hàm find mà ô mock cái findOne luôn thì cũng như ông đang tự tạo ra 1 khối data và đem đi so sánh với chính nó v :))

2021-08-23 04:19 UTC, danghieuliem commented on packages/server/src/modules/academic/academic.service.spec.ts
> +          .mockResolvedValueOnce(lesson as ANY)
thì đúng như tích chất của test mà ông

2021-08-23 13:36 UTC, canhuyh approved these changes

2021-08-23 13:44 UTC, merged